# BEGIN_KITTY_FONTS
font_family      family="Noto Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Aquarium Dark
include current-theme.conf
# END_KITTY_THEME

font_size 11.0
cursor_shape underline
cursor_blink_interval 0
cursor_trail 3
window_padding_width 20
tab_bar_edge top
tab_bar_margin_height 20 0
tab_bar_style slant
tab_bar_align start
tab_bar_show_new_tab_button yes
tab_bar_min_tabs 0
tab_powerline_style angled
editor /snap/bin/code
background #181924
tab_bar_background #252525
tab_bar_margin_color #252525
active_tab_foreground   #ffffff
active_tab_background   #003e90
active_tab_font_style   bold-italic
inactive_tab_foreground #010101
inactive_tab_background #525252
inactive_tab_font_style normal
font_family      family="PT Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
enabled_layouts splits
map cmd+shift+e launch --cwd=current --location=vsplit
map cmd+shift+d launch --cwd=current --location=hsplit
map cmd+t new_tab_with_cwd

# nova aba herda o diretório da aba atual (ctrl+shift+t e qualquer outro map new_tab)
action_alias new_tab new_tab_with_cwd
map kitty_mod+t new_tab_with_cwd
